# Generated by Django 3.2.4 on 2026-01-05 02:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hexparser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A2LFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'A2L文件',
                'db_table': 'cal_a2l_file',
            },
        ),
        migrations.CreateModel(
            name='A2LModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'A2L模块',
                'db_table': 'cal_a2l_module',
            },
        ),
        migrations.CreateModel(
            name='AxisDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, default='', max_length=32, verbose_name='轴属性')),
                ('input_quantity', models.CharField(blank=True, default='', max_length=64, verbose_name='输入量')),
                ('conversion_method', models.CharField(blank=True, default='', max_length=64, verbose_name='转换方法名')),
                ('max_axis_points', models.PositiveIntegerField(default=0, verbose_name='最大轴点数')),
                ('lower_limit', models.FloatField(verbose_name='下限')),
                ('upper_limit', models.FloatField(verbose_name='上限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轴描述',
                'db_table': 'cal_axis_descr',
            },
        ),
        migrations.CreateModel(
            name='Coeffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(default=0, verbose_name='系数a')),
                ('b', models.FloatField(default=1, verbose_name='系数b')),
                ('c', models.FloatField(default=0, verbose_name='系数c')),
                ('d', models.FloatField(default=0, verbose_name='系数d')),
                ('e', models.FloatField(default=0, verbose_name='系数e')),
                ('f', models.FloatField(default=1, verbose_name='系数f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '换算系数',
                'verbose_name_plural': '换算系数',
                'db_table': 'cal_coeffs',
                'unique_together': {('a', 'b', 'c', 'd', 'e', 'f')},
            },
        ),
        migrations.CreateModel(
            name='CompuMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='转换方法名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('conversion_type', models.CharField(choices=[('IDENTICAL', '恒等转换'), ('LINEAR', '线性转换'), ('RAT_FUNC', '有理函数转换'), ('TAB_INTP', '插值查表'), ('TAB_NOINTP', '非插值查表'), ('TAB_VERB', '文本查表'), ('FORM', '公式转换')], default='RAT_FUNC', max_length=32, verbose_name='转换类型')),
                ('format_str', models.CharField(blank=True, default='', max_length=32, verbose_name='格式化字符串')),
                ('units', models.CharField(blank=True, default='', max_length=32, verbose_name='单位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a2l_file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a2l_compu_methods', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
                ('coefficient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coefficient_compu_method', to='hexparser.coeffs', verbose_name='换算方法')),
            ],
            options={
                'verbose_name': '转换方法定义',
                'db_table': 'cal_compu_method',
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_type', models.CharField(default='HEX', max_length=32, verbose_name='文件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据文件',
                'db_table': 'cal_data_file',
            },
        ),
        migrations.CreateModel(
            name='Maturity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板说明')),
                ('value', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='成熟度(0~1)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成熟度',
                'db_table': 'cal_maturity',
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='工作包名称')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父模块id')),
                ('owner', models.CharField(max_length=32, verbose_name='拥有人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='删除')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '标定工作包',
                'db_table': 'cal_work_package',
            },
        ),
        migrations.CreateModel(
            name='RecordLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_layouts', to='hexparser.a2lmodule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': 'A2L记录布局',
                'db_table': 'cal_record_layout',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='参数名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('characteristic_type', models.CharField(choices=[('VALUE', '标量值'), ('VAL_BLK', '值块'), ('MAP', '映射表'), ('CURVE', '曲线')], default='VALUE', max_length=32, verbose_name='参数类型')),
                ('ecu_address', models.BigIntegerField()),
                ('record_layout', models.CharField(choices=[('Scalar_UBYTE', '8位无符号整数'), ('Scalar_SBYTE', '8位有符号整数'), ('Scalar_UWORD', '16位无符号整数'), ('Scalar_SWORD', '16位有符号整数'), ('Scalar_ULONG', '32位无符号整数'), ('Scalar_SLONG', '32位有符号整数'), ('Scalar_FLOAT32_IEEE', '32位浮点数'), ('Scalar_FLOAT64_IEEE', '64位浮点数'), ('Array_UBYTE', '8位无符号整数数组'), ('Array_SBYTE', '8位有符号整数数组'), ('Array_UWORD', '16位无符号整数数组'), ('Array_SWORD', '16位有符号整数数组'), ('Array_ULONG', '32位无符号整数数组'), ('Array_SLONG', '32位有符号整数数组'), ('Array_FLOAT32_IEEE', '32位浮点数组'), ('Array_FLOAT64_IEEE', '64位浮点数组'), ('Map_FLOAT32_IEEE', '32位浮点映射表'), ('Map_UBYTE', '8位无符号整数映射表'), ('Map_SBYTE', '8位有符号整数映射表'), ('Map_UWORD', '16位无符号整数映射表'), ('Map_SWORD', '16位有符号整数映射表')], max_length=64, verbose_name='记录布局')),
                ('max_diff', models.FloatField(blank=True, default=0.0, verbose_name='最大差值')),
                ('lower_limit', models.FloatField(verbose_name='下限')),
                ('upper_limit', models.FloatField(verbose_name='上限')),
                ('number', models.PositiveIntegerField(default=0, help_text='仅非VALUE类型有效', verbose_name='个数')),
                ('is_key', models.BooleanField(default=False, verbose_name='是否为关键标定量')),
                ('edit_upper_limit', models.FloatField(default=-1, help_text='默认-1表示尚未填写', verbose_name='标定量填写范围上限')),
                ('edit_lower_limit', models.FloatField(default=-1, help_text='默认-1表示尚未填写', verbose_name='标定量填写范围下限')),
                ('related_test_cases', models.CharField(default='', max_length=256, verbose_name='标定的相关测试用例')),
                ('pass_standard', models.CharField(default='', max_length=256, verbose_name='标定涉及通过标准')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updater', models.CharField(max_length=64, verbose_name='更新人')),
                ('a2l_file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a2l_characteristics', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
                ('conversion_method', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversion_characteristics', to='hexparser.compumethod', verbose_name='转换方法')),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_characteristics', to='hexparser.a2lmodule', verbose_name='所属模块')),
                ('work_package', models.ForeignKey(db_constraint=False, default=hexparser.models.get_default_unbound_work_package, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wp_characteristics', to='hexparser.workpackage', verbose_name='关联标定工作包')),
            ],
            options={
                'verbose_name': '标定参数定义',
                'db_table': 'cal_characteristic',
                'unique_together': {('a2l_file', 'name', 'ecu_address', 'conversion_method')},
            },
        ),
        migrations.CreateModel(
            name='AxisPtsX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('datatype', models.CharField(max_length=64, verbose_name='datatype')),
                ('index_incr', models.CharField(max_length=32, verbose_name='indexIncr')),
                ('addressing', models.CharField(max_length=32, verbose_name='addressing')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_layout', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='axis_pts_x', to='hexparser.recordlayout', verbose_name='关联记录布局')),
            ],
            options={
                'verbose_name': 'A2L记录布局-AXIS_PTS_X',
                'db_table': 'cal_axis_pts_x',
            },
        ),
        migrations.CreateModel(
            name='AxisPtsRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_points', models.CharField(max_length=64, verbose_name='轴点引用名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('axis_descr', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='axis_pts_ref', to='hexparser.axisdescr', verbose_name='关联轴描述')),
            ],
            options={
                'verbose_name': '轴点引用',
                'db_table': 'cal_axis_pts_ref',
            },
        ),
        migrations.AddField(
            model_name='axisdescr',
            name='characteristic',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristic_axis_descrs', to='hexparser.characteristic', verbose_name='关联标定参数'),
        ),
        migrations.CreateModel(
            name='A2LProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a2l_file', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
            ],
            options={
                'verbose_name': 'A2L工程',
                'db_table': 'cal_a2l_project',
                'unique_together': {('a2l_file', 'name')},
            },
        ),
        migrations.AddField(
            model_name='a2lmodule',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='hexparser.a2lproject', verbose_name='所属工程'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='参数名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('datatype', models.CharField(choices=[('UBYTE', '8位无符号整数'), ('SBYTE', '8位有符号整数'), ('UWORD', '16位无符号整数'), ('SWORD', '16位有符号整数'), ('ULONG', '32位无符号整数'), ('SLONG', '32位有符号整数'), ('FLOAT32_IEEE', '32位浮点数'), ('FLOAT64_IEEE', '64位浮点数'), ('A_UINT8', '8位无符号整数数组'), ('A_INT8', '8位有符号整数数组'), ('A_UINT16', '16位无符号整数数组'), ('A_INT16', '16位有符号整数数组'), ('A_UINT32', '32位无符号整数数组'), ('A_INT32', '32位有符号整数数组'), ('A_FLOAT32_IEEE', '32位浮点数数组'), ('A_FLOAT64_IEEE', '64位浮点数数组')], max_length=32, verbose_name='数据类型')),
                ('resolution', models.PositiveIntegerField(blank=True, default=0, verbose_name='分辨率')),
                ('accuracy', models.FloatField(blank=True, default=0.0, verbose_name='精度')),
                ('lower_limit', models.FloatField(verbose_name='下限')),
                ('upper_limit', models.FloatField(verbose_name='上限')),
                ('ecu_address', models.BigIntegerField()),
                ('metadata', models.JSONField(default=dict, help_text='记录原始数据', verbose_name='元数据')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a2l_file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a2l_measurements', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
                ('conversion_method', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversion_measurements', to='hexparser.compumethod', verbose_name='转换方法')),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_measurements', to='hexparser.a2lmodule', verbose_name='所属模块')),
                ('work_package', models.ForeignKey(db_constraint=False, default=hexparser.models.get_default_unbound_work_package, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wp_measurements', to='hexparser.workpackage', verbose_name='关联标定工作包')),
            ],
            options={
                'verbose_name': '测量量定义',
                'db_table': 'cal_measurement',
                'unique_together': {('a2l_file', 'name', 'ecu_address', 'conversion_method')},
            },
        ),
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=0, verbose_name='行号')),
                ('byte_count', models.PositiveSmallIntegerField(default=0, verbose_name='ll 本行字节数')),
                ('offset_addr', models.PositiveIntegerField(default=0, verbose_name='aaaa 偏移地址')),
                ('record_type', models.PositiveSmallIntegerField(default=0, verbose_name='tt 记录类型')),
                ('data_bytes', models.BinaryField(blank=True, default=b'', verbose_name='数据dd（二进制）')),
                ('checksum', models.PositiveSmallIntegerField(default=0, verbose_name='cc 校验和')),
                ('current_value', models.JSONField(blank=True, default=list, help_text='统一存为数组：VALUE类型[value]，MAP/CURVE存多元素数组', verbose_name='当前标定值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('characteristic', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='characteristic_values', to='hexparser.characteristic', verbose_name='关联标定参数')),
                ('hex_file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hex_values', to='hexparser.datafile', verbose_name='关联HEX数据文件')),
                ('maturity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maturity_values', to='hexparser.maturity', verbose_name='成熟度')),
            ],
            options={
                'verbose_name': 'HEX数据记录',
                'db_table': 'cal_hex',
                'unique_together': {('hex_file', 'characteristic', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='AxisPts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='轴点名称')),
                ('long_identifier', models.TextField(blank=True, default='', verbose_name='长标识符')),
                ('address', models.BigIntegerField(verbose_name='ECU地址')),
                ('input_quantity', models.CharField(blank=True, default='', max_length=64, verbose_name='输入量')),
                ('record_layout', models.CharField(blank=True, default='', max_length=64, verbose_name='存储属性')),
                ('max_diff', models.FloatField(default=0.0, verbose_name='最大差值')),
                ('conversion_method', models.CharField(blank=True, default='', max_length=64, verbose_name='转换方法名')),
                ('max_axis_points', models.PositiveIntegerField(default=0, verbose_name='最大轴点数')),
                ('lower_limit', models.FloatField(verbose_name='下限')),
                ('upper_limit', models.FloatField(verbose_name='上限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a2l_file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='a2l_axis_pts', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_axis_pts', to='hexparser.a2lmodule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '轴点定义',
                'db_table': 'cal_axis_pts',
                'unique_together': {('a2l_file', 'name', 'address', 'conversion_method')},
            },
        ),
        migrations.CreateModel(
            name='Asap2Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveSmallIntegerField(help_text='ASAP2 主版本号，如 1', verbose_name='版本号')),
                ('upgrade_no', models.PositiveSmallIntegerField(help_text='ASAP2 升级版本号，如 71', verbose_name='升级号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a2l_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asap2_versions', to='hexparser.a2lfile', verbose_name='关联A2L文件')),
            ],
            options={
                'verbose_name': 'ASAP2版本信息',
                'verbose_name_plural': 'ASAP2版本信息',
                'db_table': 'cal_asap2_version',
                'unique_together': {('a2l_file', 'version_no', 'upgrade_no')},
            },
        ),
        migrations.CreateModel(
            name='A2LModuleParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_identifier', models.CharField(max_length=128, verbose_name='版本标识')),
                ('supplier', models.CharField(blank=True, default='', max_length=128, verbose_name='供应商')),
                ('customer', models.CharField(blank=True, default='', max_length=128, verbose_name='客户')),
                ('customer_no', models.CharField(blank=True, default='', max_length=128, verbose_name='客户编号')),
                ('user', models.CharField(blank=True, default='', max_length=64, verbose_name='用户')),
                ('phone_no', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('ecu', models.CharField(blank=True, default='', max_length=64, verbose_name='ECU名称')),
                ('cpu_type', models.CharField(blank=True, default='', max_length=64, verbose_name='CPU类型')),
                ('no_of_interfaces', models.PositiveIntegerField(default=1, verbose_name='接口数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_parameters', to='hexparser.a2lmodule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': 'A2L模块参数',
                'db_table': 'cal_a2l_module_parameter',
                'unique_together': {('module', 'version_identifier', 'ecu', 'cpu_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='a2lmodule',
            unique_together={('project', 'name')},
        ),
    ]
